### ISSUE TITLE
No authorisation check for API connections

### ISSUE THREAD

**Issue by dhilton** [tsuru/postgres-api#16]
Although the service.yaml.example documents that you should set a username / password, the Flask application has no authorisation check to stop an unauthorised client.

**Comment by fsouza** [comment]
@dhilton thanks for reporting it!

**Comment by dhilton** [comment]
Happy to fix it - have implemented it here previously: https://github.com/alphagov/elastic-search-api/blob/master/api.py#L10

**Comment by fsouza** [comment]
@dhilton nice fix! Could you do it then? Happy to merge the change!

Would you be interested in getting the changes in the elastic-search-api merged upstream as well?

**Comment by dhilton** [comment]
On the first; yes.

On the second - I'll see if we can, still needs work to make it more robust, be great to add proper isolation and such like.

**Comment by fsouza** [comment]
@dhilton is it fine to close this issue now?

**Comment by dhilton** [comment]
Yes - always be closin'
