### ISSUE TITLE
Can't use a database name with an Uppercase letter

### ISSUE THREAD

**Issue by dhilton** [tsuru/postgres-api#8]
To reproduce:
1. Create a new service instance of the Postgresql API `pTest12`
2. Reports the DB has been created
3. Try to bind the DB instance to your app

Error log:

```
Error: Failed to bind the instance "pTest12" to the app "dashboard": FATAL: database "pTest12" does not exist
```

Root cause analysis:
http://www.postgresql.org/docs/current/static/sql-syntax-lexical.html

Postgresql treats the db name as lowercase, normalising. However, the field in the postgresapi does not replicate this behaviour, thus allowing you to create a database with Capital letters. The fix could be to warn the user that no uppercase letters are allowed in the db aname and to add in a validation rule to the API to stop a user creating such a database.

**Comment by philiptzou** [comment]
Well, we can actually allow uppercase by using some little trick:

In function [`canonicalize_db_name`](https://github.com/tsuru/postgres-api/blob/master/postgresapi/models.py#L46):

``` python
def canonicalize_db_name(name):
    if re.search(r"[A-Z\W\s]", name) is not None:
        suffix = hashlib.sha1(name).hexdigest()[:10]
        name = name[:1].lower() + name[1:]
        name = re.sub(r"[A-Z]", lambda m: "_" + m.group(0).lower(), name)
        name = re.sub(r"[\W\s]", "_", name) + suffix
    return name
```

It should work.
